INSERT INTO users (name, age) VALUES ("Kim", 38);
INSERT INTO users (name, age) VALUES ("Kanye", 42);
INSERT INTO users (name, age) VALUES ("Khloe", 38);
INSERT INTO users (name, age) VALUES ("Kourtney", 45);
INSERT INTO users (name, age) VALUES ("JJ", 28);
INSERT INTO users (name, age) VALUES ("Joe", 45);
INSERT INTO users (name, age) VALUES ("Elon", 38);
INSERT INTO users (name, age) VALUES ("Tim", 59);
INSERT INTO users (name, age) VALUES ("Cameron", 68);
INSERT INTO users (name, age) VALUES ("Ebenezer", 79);
INSERT INTO users (name, age) VALUES ("Chad III", 24);
INSERT INTO users (name, age) VALUES ("Lara", 26);
INSERT INTO users (name, age) VALUES ("Myra", 47);
INSERT INTO users (name, age) VALUES ("Janet", 55);
INSERT INTO users (name, age) VALUES ("Manny", 33);
INSERT INTO users (name, age) VALUES ("Karen", 52);
INSERT INTO users (name, age) VALUES ("Eenie", 40);
INSERT INTO users (name, age) VALUES ("Meenie", 40);
INSERT INTO users (name, age) VALUES ("Minie", 40);
INSERT INTO users (name, age) VALUES ("Moe", 40);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Feed the Kittens", "charity", 5000.00, '2021-02-10', '2021-05-01)');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Music for the Masses", "music", 9500.00, '2021-05-01', '2021-06-01)');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Food for Your Hood", "charity", 7800.00, '2021-01-01', '2021-02-01)');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Bono is Back", "music", 350.00, '2021-03-01', '2021-04-01)');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("School Supplies for Penguin ES", "charity", 5000.00, '2021-06-15', '2021-09-01)');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Soul Searching", "music", 200.00, '2021-02-10', '2021-02-15)');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Monet in the Making", "art", 6000.00, '2021-03-15', '2021-05-31)');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Farms Fresh", "charity", 1000.00, '2021-02-01', '2021-12-01)');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Museums Galore", "art", 1200.00, '2021-07-01', '2021-08-01)');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Feed the Puppies", "charity", 5000.00, '2021-02-10', '2021-05-01)');

INSERT INTO pledges (amount, user_id, project_id) VALUES (250.50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20.75, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600.00, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (900.00, 2, 20);
INSERT INTO pledges (amount, user_id, project_id) VALUES (66.66, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50.00, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20.00, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (296.00, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100.00, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300.00, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (99.99, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (12.50, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (60.00, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200.00, 5, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (250.50, 6, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5.00, 6, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1.00, 6, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100.00, 7, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 7, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20.00, 7, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50.00, 8, 11);
INSERT INTO pledges (amount, user_id, project_id) VALUES (12.20, 8, 12);
INSERT INTO pledges (amount, user_id, project_id) VALUES (12.34, 8, 13);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40.00, 9, 14);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300.00, 9, 15);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50.50, 9, 16);
INSERT INTO pledges (amount, user_id, project_id) VALUES (29.00, 10, 17);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10.00, 10, 18);
INSERT INTO pledges (amount, user_id, project_id) VALUES (29.50, 10, 19);

